/**
 * Local git helpers for the build pipeline.
 * No remote or GitHub required — everything stays in outputDir.
 * Uses git worktrees so parallel nodes can commit on separate branches simultaneously.
 */
import { execFile } from 'child_process';
import { promisify } from 'util';
import { writeFile } from 'fs/promises';
import path from 'path';

const exec = promisify(execFile);

export interface GitContext {
  /** Absolute path to the main working tree (owns .git). */
  outputDir: string;
}

export function branchSlug(text: string, max = 36): string {
  return text.toLowerCase().slice(0, max)
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'module';
}

/** Init a fresh local repo in outputDir with an initial commit. */
export async function initLocalRepo(outputDir: string, problemTitle: string): Promise<GitContext> {
  // git init (idempotent)
  await exec('git', ['init', '-b', 'main'], { cwd: outputDir }).catch(async () => {
    await exec('git', ['init'], { cwd: outputDir });
    await exec('git', ['checkout', '-b', 'main'], { cwd: outputDir }).catch(() => {});
  });

  // configure a local identity so commits don't fail if global config is absent
  await exec('git', ['config', 'user.email', 'anamorphic@local'], { cwd: outputDir }).catch(() => {});
  await exec('git', ['config', 'user.name', 'anamorphic'], { cwd: outputDir }).catch(() => {});

  await writeFile(
    path.join(outputDir, 'README.md'),
    `# build\n\n**Problem:** ${problemTitle}\n\nGenerated by anamorphic.\n`,
  );
  await exec('git', ['add', 'README.md'], { cwd: outputDir });
  await exec('git', ['commit', '-m', 'chore: init'], { cwd: outputDir });

  return { outputDir };
}

/**
 * Create a git worktree on a new branch.
 * Returns the absolute path to the worktree directory.
 * Worktrees are siblings of outputDir so they're outside the main working tree.
 */
export async function createWorktree(ctx: GitContext, branch: string): Promise<string> {
  const worktreeDir = path.resolve(ctx.outputDir, '..', `.wt-${branch}`);
  await exec('git', ['worktree', 'add', '-b', branch, worktreeDir, 'main'], { cwd: ctx.outputDir });
  return worktreeDir;
}

/** Write a file, stage it, and commit in the given directory (worktree or main). */
export async function stageAndCommit(
  dir: string,
  filename: string,
  content: string,
  message: string,
): Promise<void> {
  await writeFile(path.join(dir, filename), content, 'utf8');
  await exec('git', ['add', filename], { cwd: dir });
  // --allow-empty guards against identical WIP commits
  await exec('git', ['commit', '--allow-empty', '-m', message], { cwd: dir });
}

/** Remove a worktree after the branch work is done. */
export async function removeWorktree(ctx: GitContext, worktreeDir: string): Promise<void> {
  await exec('git', ['worktree', 'remove', '--force', worktreeDir], { cwd: ctx.outputDir }).catch(() => {});
}
