export type { ArtifactType, ValidatorSpec, MorphismBody, Autonomy, Term } from './types.js';
export { id, morphism, compose, tensor, trace, composeAll, tensorAll, UnitType, productType, isUnit, typeToString } from './types.js';
export type { MorphismType } from './type-check.js';
export { typesEqual, inferType, typeCheck, TypeError } from './type-check.js';
export type { Artifact, ExecutionNode, BodyExecutor } from './executor.js';
export { buildGraph, execute } from './executor.js';
export type { ValidationResult } from './validate.js';
export { validate } from './validate.js';
export type { Factoring } from './factor.js';
export { applyFactoring } from './factor.js';
